name: Continuous Deployment for Backend
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: backend
          file: ./backend/Dockerfile
          push: true
          tags: sarthaksbiswas29/dubsh:${{ github.sha }}

      - name: Executing Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            port: 22
            script: |
              docker pull sarthaksbiswas29/dubsh:${{ github.sha }}
              docker stop dubsh
              docker rm dubsh
              docker run -p 3000:3000 --name dubsh --env-file=.secrets/backend.env -d sarthaksbiswas29/dubsh:${{ github.sha }}